# Generated by Django 5.0 on 2024-01-12 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=150)),
                ('Discreption', models.TextField()),
                ('Category', models.CharField(choices=[('starter', 'starter'), ('Paneer', 'Paneer'), ('Rice', 'Rice'), ('Chineese', 'Chineese'), ('StreetFood', 'StreetFood'), ('StateSpecial', 'StateSpecial')], max_length=20)),
                ('image', models.ImageField(upload_to='static/images')),
                ('author', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
