# Generated by Django 5.0 on 2024-01-19 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_recipe_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='selected_option',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
