# Generated by Django 5.0 on 2024-01-19 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_recipe_selected_option'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='selected_option',
        ),
    ]
